version: '3.8'
services:
  app:
    build:
      context: .
    image: aplicacao-spring
    container_name: app-spring
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gerenciamento_cliente
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=gabrielmira.empiricus@gmail.com
      - SPRING_MAIL_PASSWORD=veee typi eqzk iqpe
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED=true
      - API_SECURITY_TOKEN_SECRET=senhatoken
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciamento_cliente
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: